doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AcMarche\Travaux:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AcMarche/Travaux/src/Entity'
                prefix: 'AcMarche\Travaux'
                alias: AcMarche\Travaux
            AcMarche\Avaloir:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AcMarche/Avaloir/Entity'
                prefix: 'AcMarche\Avaloir'
                alias: AcMarche\Avaloir
            AcMarche\Stock:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/AcMarche/Stock/Entity'
                prefix: 'AcMarche\Stock'
                alias: AcMarche\Stock
