kernel:
    resource: ../../src/App/Kernel.php
    type: annotation

travaux:
    resource: ../../src/AcMarche/Travaux/src/Controller/
    type: annotation

avaloir:
    # loads routes from the PHP annotations of the controllers found in that directory
    resource: '../../src/AcMarche/Avaloir/Controller/'
    type:     annotation
    prefix: avaloirs/

stock:
    # loads routes from the PHP annotations of the controllers found in that directory
    resource: '../../src/AcMarche/Stock/Controller/'
    type:     annotation
    prefix: stock/
