# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    ac_marche_travaux.upload.directory: "%kernel.project_dir%/public/files"
    ac_marche_travaux.download.directory: "/files"
    router.request_context.host: '%env(APP_URL)%'
    router.request_context.scheme: http
    ac_marche_avaloir_destinataire: '%env(AVALOIR_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    AcMarche\Travaux\:
        resource: '../src/AcMarche/Travaux'
        exclude: '../src/AcMarche/Travaux/{Entity,Migrations,Tests,Kernel.php}'

    AcMarche\Travaux\Controller\:
        resource: '../src/AcMarche/Travaux/Controller/'
        public: true
        tags: ['controller.service_arguments']

    AcMarche\Avaloir\:
        resource: '../src/AcMarche/Avaloir'
        exclude: '../src/AcMarche/Avaloir/{Entity,Migrations,Tests,Kernel.php}'

    AcMarche\Avaloir\Controller\:
        resource: '../src/AcMarche/Avaloir/Controller/'
        public: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    AcMarche\Travaux\Service\InterventionWorkflow:
        public: true
        arguments:
            $workflow: '@state_machine.intervention_publication'

    AcMarche\Travaux\Security\StaffLdap:
        $host: '%env(ACLDAP_URL)%'
        $dn: '%env(ACLDAP_DN)%'
        $user: '%env(ACLDAP_USER)%'
        $password: '%env(ACLDAP_PASSWORD)%'
