liip_imagine:
    filter_sets:
      cache: ~
      actravaux_thumb:
        quality: 95
        cache: default
        filters:
          thumbnail: { size: [250, 188], mode: outbound }
      aval_thumb:
        quality: 95
        cache: default
        filters:
          thumbnail: { size: [150, 70], mode: outbound }
      actravaux_zoom:
        quality: 95
        cache: default
        filters:
          thumbnail: { size: [1024, 768], mode: inset }
      avaloir_thumb:
        quality: 95
        cache: default
        filters:
          thumbnail: { size: [800, 600], mode: outbound }
      avaloir_heighten_filter:
        filters:
          # use and setup the "relative_resize" filter
          relative_resize:
            # given 50x40px, output 75x60px using "heighten" option
            heighten: 600

