twig:
  form_themes: ['bootstrap_4_layout.html.twig']
  paths:
    '%kernel.project_dir%/src/AcMarche/Stock/templates': AcMarcheStock
    '%kernel.project_dir%/src/AcMarche/Avaloir/templates': AcMarcheAvaloir
