vich_uploader:
    mappings:
        taxes:
            uri_prefix: /files/interventions
            upload_destination: '%kernel.project_dir%/public/files/interventions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
